spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      forace: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/vue
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update #create1
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    session:
      cookie:
        httponly: false
logging:
  config: classpath:log4j2.xml
